version: 1.0.{build}
image: Visual Studio 2019
build_script:
- cmd: >-
    dotnet restore

    dotnet build
test_script:
- cmd: dotnet test
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t $env:CODECOV_TOKEN
